language: php
php:
    - 7.2
    - 7.3
    - 7.4
before_install:
    - phpenv config-rm xdebug.ini || true

install:
  - if [[ "$DEPS" = 'high' ]]; then travis_retry composer --no-interaction --no-suggest update; fi
  - if [[ "$DEPS" = 'low' ]]; then travis_retry composer --no-interaction --no-suggest --prefer-lowest --prefer-stable update; fi
  - if [[ "$DEPS" = 'stable' ]]; then travis_retry composer --no-interaction --no-suggest --prefer-stable update; fi

script: composer run-script --timeout=0 check

env:
    matrix:
        - DEPS=low
        - DEPS=high
        - DEPS=stable
cache:
  directories:
    - $(composer config cache-files-dir)
